name: pure-noise
version: 0.2.0.0
github: "jtnuttall/pure-noise"
license: BSD-3-Clause
author: "Jeremy Nuttall"
maintainer: "jeremy@jeremy-nuttall.com"
copyright: "2024 Jeremy Nuttall"

extra-source-files:
  - README.md

extra-doc-files:
  - CHANGELOG.md

synopsis: High-performance composable noise generation (Perlin, Simplex, Cellular)
category: Math, Numeric, Noise

description: |
  A high-performance noise generation library ported from FastNoiseLite.
  Provides N-dimensional noise functions (Perlin, OpenSimplex, SuperSimplex,
  Value, Cellular) that can be composed using Num or Fractional methods with
  minimal performance overhead. Noise values are generally clamped to [-1, 1].
  Benefits significantly from LLVM backend compilation (~50-80% performance improvement).

language: GHC2021

dependencies:
  - base >= 4.16 && < 5
  - primitive >= 0.8 && < 0.10

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Numeric.Noise
    - Numeric.Noise.Cellular
    - Numeric.Noise.Fractal
    - Numeric.Noise.OpenSimplex
    - Numeric.Noise.Perlin
    - Numeric.Noise.SuperSimplex
    - Numeric.Noise.Value
    - Numeric.Noise.ValueCubic

tests:
  pure-noise-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
      - -Wno-missing-export-lists
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pure-noise
      - aeson >= 2.0 && < 2.3
      - aeson-pretty
      - bytestring
      - directory
      - filepath
      - JuicyPixels >= 3.3 && < 3.4
      - massiv >= 1.0 && < 2.0
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - tasty-golden

benchmarks:
  pure-noise-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N +RTS -A32m --nonmoving-gc -T -RTS
      - -O2
      - -optc-O3
      - -fsimpl-tick-factor=1000
    dependencies:
      - pure-noise
      - deepseq
      - massiv >= 1.0 && < 2.0
      - random
      - tasty
      - tasty-bench
      - vector <= 0.14
