name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  GHC_VERSION: 9.6.6
  CACHE_BUST_VERSION: v0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.5
        with:
          version: 15
      - id: stack
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: ""
          cache-prefix: ${{ env.CACHE_BUST_VERSION }}

      # - uses: haskell-actions/setup@v2
      #   if: steps.ghcup.outputs.cache-hit != 'true'
      #   with:
      #     ghc-version: ${{ env.GHC_VERSION }}
      #     enable-stack: true
      #     stack-version: latest

      # - name: Build
      #   run: |
      #     stack build --ghc-options -fllvm

      # - name: Test
      #   run: |
      #     stack test --ghc-options -fllvm

      # - name: Bench
      #   run: |
      #     stack bench --ghc-options -fllvm --ba='+RTS -T -RTS'
