name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CACHE_BUST_VERSION: v0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.5
        with:
          version: 15
      - id: stack
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: "--ghc-options -fllvm"
          cache-prefix: ${{ env.CACHE_BUST_VERSION }}

      - name: test
        run: stack test --ghc-options -fllvm

      - name: bench
        run: stack bench --ghc-options -fllvm --ba='+RTS -T -RTS'
